name: hawaiiheals
favicon: null
layout_spectrum: 0.04386400827206671
typography_spectrum: 0.4791199453175068
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.8023815336637199
  lightness: 0.8070406508632004
  saturation: 0.2172746160067618
  rhythmicContrast: 0.3978609701152891
purpose: []
